version: '2.5'
services:
  skycalendarapp:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sky-krono-app
    container_name: sky-krono-app
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "7575:80"